# Generated by Django 2.2.2 on 2020-10-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='This books does not contain any description. Please refer to author and title of the Book'),
        ),
    ]
