# Generated by Django 2.2.2 on 2020-10-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(default='default.pdf', upload_to='pdf'),
        ),
    ]
